# Generated by Django 2.1.9 on 2019-06-03 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubDate', models.DateTimeField(auto_now_add=True, verbose_name='评论日期')),
                ('content', models.TextField(max_length=600, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsName', models.CharField(max_length=100, verbose_name='商品名称')),
                ('pubDate', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('goodsType', models.CharField(choices=[('1', '书籍'), ('2', '手机'), ('3', '电脑'), ('4', '衣服'), ('5', '其他')], max_length=1, verbose_name='商品种类')),
                ('productIntroduction', models.TextField(verbose_name='商品简介')),
                ('goodsPrice', models.FloatField(verbose_name='商品价格')),
                ('goodsNum', models.PositiveIntegerField(default=0, verbose_name='商品数量')),
                ('goodsSelected', models.PositiveIntegerField(default=0, verbose_name='商品被选中数量')),
                ('goodssales', models.PositiveIntegerField(default=0, verbose_name='商品销售量')),
                ('goodsPic', models.ImageField(blank=True, default='goods/default_goods.png', null=True, storage=store.models.ImageStorage(), upload_to='goods/', verbose_name='商品图片')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='收货人')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('telephone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('total', models.FloatField(verbose_name='总金额')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='购买数量')),
                ('subtotal', models.FloatField(blank=True, null=True, verbose_name='小计')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='购买数量')),
                ('subtotal', models.FloatField(verbose_name='小计')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Goods')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Goods'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
