# Generated by Django 2.1.9 on 2019-06-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190619_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='major',
            field=models.TextField(blank=True, default='', null=True, verbose_name='个人简介'),
        ),
    ]
