# Generated by Django 2.1.9 on 2019-06-20 08:51

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('telephone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('avatar', models.ImageField(default='avatar/default_avatar.png', storage=user.models.ImageStorage(), upload_to='avatar/', verbose_name='头像')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='地址')),
                ('major', models.TextField(blank=True, default='', verbose_name='个人简介')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
