# Generated by Django 2.1.9 on 2019-06-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_goods',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='order_goods',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order_goods',
        ),
    ]
